apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
  namespace: devops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: 603761645100.dkr.ecr.eu-west-1.amazonaws.com/devops-project-repo:react-latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: devops-app-config
