apiVersion: v1
kind: Service
metadata:
  name: react-app-service
  namespace: devops-app
spec:
  type: LoadBalancer
  selector:
    app: react-app
  ports:
    - port: 80
      targetPort: 80
