name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push React image
        run: |
          docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/devops-project-repo:react-latest ./app
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/devops-project-repo:react-latest

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name dp-cluster


      - name: Apply aws-auth
        run: kubectl apply -f kubernetes/aws-auth.yaml


      - name: Create Kubernetes secret
        run: |
          kubectl create secret generic devops-app-secret \
            --from-literal=DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
            --from-literal=B_HOST=$"{{ secrets.DB_HOST }}" \
            --from-literal=DB_PORT="5432" \
            --from-literal=PGADMIN_EMAIL=$"{{ secrets.PGADMIN_EMAIL }}" \
            --from-literal=PGADMIN_PASSWORD=$"{{ secrets.PGADMIN_PASSWORD }}" \
            --namespace=devops-app \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f kubernetes/namespace.yaml
          kubectl apply -f kubernetes/configmap.yaml
          kubectl apply -f kubernetes/deployment.yaml
          kubectl apply -f kubernetes/service.yaml
          kubectl apply -f kubernetes/pgadmin/deployment.yaml
          kubectl apply -f kubernetes/pgadmin/service.yaml

      - name: Restart React deployment
        run: |
          kubectl rollout restart deployment/react-app -n devops-app
